name: 测试例程

on: push

jobs:
  Spear-build:
    name: 编译Spear相关文件
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # 请根据需要选择合适的 Go 版本

      - name: Verify Go version
        run: go version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Verify Python version
        run: python --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: 安装依赖并且编译文件
        run: |
          sudo apt install portaudio19-dev
          ls -l
          ip addr show
          make